### ISSUE TITLE
Exception thrown while trying to setup es 2.2.0 

### ISSUE THREAD

**Issue by salimane** [meltwater/puppet-es#22]
I was trying to setup the latest version of elasticsearch version 2.2.0 with the following configurations: 
```puppet
---
classes:
  - es::instances

es::instances::instance:
  my_lovely_es:
    clustername: my_lovely_es
    es_http_port_range: 9200
    es_tcp_port_range: 9300
    multicast: false
    es_unicast_hosts: 'vagrant.my_lovely_es.com:9300'
    es_url: 'https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.0/elasticsearch-2.2.0.tar.gz'
    version: 2.2.0
    script_disable_dynamic: false
    xms: '2048m'
    xmx: '2048m'
    number_of_shards: '5'
    number_of_replicas: 0
    cluster_nodes: '1'
    minimum_master_nodes: false
    marvel_install: false
    indices_cache_filter_size: '10%'
    indices_fielddata_cache_size: '10%'
    indices_fielddata_cache_expire: '-1'
    index_cache_filter_type: 'weighted'
    index_refresh_interval: '1s'
    disable_delete_all_indices: true
```

The puppet run fairly ok but failed during elasticsearch restart . The first exception I got was: 
```
[2016-02-23 16:42:48,348][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: Classpath should not contain empty elements! (outdated shell script from a previous version?) classpath=':/opt/my_lovely_es/lib/spatial4j-0.5.jar:/opt/my_lovely_es/lib/jackson-dataformat-smile-2.6.2.jar:/opt/my_lovely_es/lib/lucene-highlighter-5.4.1.jar:/opt/my_lovely_es/lib/lucene-memory-5.4.1.jar:/opt/my_lovely_es/lib/netty-3.10.5.Final.jar:/opt/my_lovely_es/lib/lucene-sandbox-5.4.1.jar:/opt/my_lovely_es/lib/jsr166e-1.1.0.jar:/opt/my_lovely_es/lib/snakeyaml-1.15.jar:/opt/my_lovely_es/lib/apache-log4j-extras-1.2.17.jar:/opt/my_lovely_es/lib/compress-lzf-1.0.2.jar:/opt/my_lovely_es/lib/jna-4.1.0.jar:/opt/my_lovely_es/lib/commons-cli-1.3.1.jar:/opt/my_lovely_es/lib/jts-1.13.jar:/opt/my_lovely_es/lib/lucene-suggest-5.4.1.jar:/opt/my_lovely_es/lib/t-digest-3.0.jar:/opt/my_lovely_es/lib/lucene-queries-5.4.1.jar:/opt/my_lovely_es/lib/compiler-0.8.13.jar:/opt/my_lovely_es/lib/lucene-spatial3d-5.4.1.jar:/opt/my_lovely_es/lib/lucene-queryparser-5.4.1.jar:/opt/my_lovely_es/lib/lucene-misc-5.4.1.jar:/opt/my_lovely_es/lib/jackson-dataformat-yaml-2.6.2.jar:/opt/my_lovely_es/lib/lucene-core-5.4.1.jar:/opt/my_lovely_es/lib/lucene-analyzers-common-5.4.1.jar:/opt/my_lovely_es/lib/guava-18.0.jar:/opt/my_lovely_es/lib/joda-convert-1.2.jar:/opt/my_lovely_es/lib/hppc-0.7.1.jar:/opt/my_lovely_es/lib/HdrHistogram-2.1.6.jar:/opt/my_lovely_es/lib/jackson-dataformat-cbor-2.6.2.jar:/opt/my_lovely_es/lib/lucene-backward-codecs-5.4.1.jar:/opt/my_lovely_es/lib/lucene-spatial-5.4.1.jar:/opt/my_lovely_es/lib/lucene-grouping-5.4.1.jar:/opt/my_lovely_es/lib/lucene-join-5.4.1.jar:/opt/my_lovely_es/lib/securesm-1.0.jar:/opt/my_lovely_es/lib/elasticsearch-2.2.0.jar:/opt/my_lovely_es/lib/joda-time-2.8.2.jar:/opt/my_lovely_es/lib/jackson-core-2.6.2.jar:/opt/my_lovely_es/lib/log4j-1.2.17.jar:/opt/my_lovely_es/lib/sigar/*'
	at org.elasticsearch.bootstrap.JarHell.parseClassPath(JarHell.java:121)
	at org.elasticsearch.bootstrap.JarHell.parseClassPath(JarHell.java:96)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:164)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

I then modify https://github.com/meltwater/puppet-es/blob/master/templates/elasticsearch.in.sh.erb#L1 with : 
```
if [ "x$ES_CLASSPATH" = "x" ]; then
    ES_CLASSPATH=$ES_HOME/lib/*:$ES_HOME/lib/sigar/*
else
	ES_CLASSPATH=$ES_CLASSPATH:$ES_HOME/lib/*:$ES_HOME/lib/sigar/*
fi
```

The next exceeption was : 
```
[2016-02-23 17:22:12,427][ERROR][bootstrap                ] Exception
java.nio.file.NoSuchFileException: /opt/my_lovely_es/lib/sigar/*
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:195)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:164)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

I then changed https://github.com/meltwater/puppet-es/blob/master/templates/elasticsearch.in.sh.erb#L1 to : 
```
if [ "x$ES_CLASSPATH" = "x" ]; then
    ES_CLASSPATH=$ES_HOME/lib/*
else
	ES_CLASSPATH=$ES_CLASSPATH:$ES_HOME/lib/*
fi
```

The next exception was then : 
```
[2016-02-23 17:27:57,107][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: Unable to access 'path.scripts' (/opt/my_lovely_es/config/scripts)
	at org.elasticsearch.bootstrap.Security.addPath(Security.java:316)
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:248)
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
	at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
	at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:196)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.AccessDeniedException: /opt/my_lovely_es/config/scripts
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
	at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
```
I wanted to ask if we need the packages ``$ES_HOME/lib/sigar/*``

cc @antonha @perbergland-meltwater 

Thanks

**Comment by antonha** [comment]
I don't really believe that this puppet module is compatible with 2.x. @bhuto is working on setting up ES 2.x with all plugins etc for the search team, maybe sync up?

**Comment by salimane** [comment]
ah ok, then it's better to just use https://forge.puppetlabs.com/elasticsearch/elasticsearch in puppet-site. It's the official one, so we should be good with any version.
what do u think @bhuto ?

**Comment by bhuto** [comment]
@salimane Yes. That one works. I am working on making sure it supports all the customizations we have. I will push my work into a branch on puppet-site today. You can check it out.

**Comment by salimane** [comment]
cool, just ping on hipchat when you do.
Thanks
